// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/chatbot.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chatbot_GetResponse_FullMethodName = "/easypwn.Chatbot/GetResponse"
)

// ChatbotClient is the client API for Chatbot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatbotClient interface {
	GetResponse(ctx context.Context, in *GetResponseRequest, opts ...grpc.CallOption) (*GetResponseResponse, error)
}

type chatbotClient struct {
	cc grpc.ClientConnInterface
}

func NewChatbotClient(cc grpc.ClientConnInterface) ChatbotClient {
	return &chatbotClient{cc}
}

func (c *chatbotClient) GetResponse(ctx context.Context, in *GetResponseRequest, opts ...grpc.CallOption) (*GetResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponseResponse)
	err := c.cc.Invoke(ctx, Chatbot_GetResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatbotServer is the server API for Chatbot service.
// All implementations must embed UnimplementedChatbotServer
// for forward compatibility.
type ChatbotServer interface {
	GetResponse(context.Context, *GetResponseRequest) (*GetResponseResponse, error)
	mustEmbedUnimplementedChatbotServer()
}

// UnimplementedChatbotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatbotServer struct{}

func (UnimplementedChatbotServer) GetResponse(context.Context, *GetResponseRequest) (*GetResponseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResponse not implemented")
}
func (UnimplementedChatbotServer) mustEmbedUnimplementedChatbotServer() {}
func (UnimplementedChatbotServer) testEmbeddedByValue()                 {}

// UnsafeChatbotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatbotServer will
// result in compilation errors.
type UnsafeChatbotServer interface {
	mustEmbedUnimplementedChatbotServer()
}

func RegisterChatbotServer(s grpc.ServiceRegistrar, srv ChatbotServer) {
	// If the following call pancis, it indicates UnimplementedChatbotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chatbot_ServiceDesc, srv)
}

func _Chatbot_GetResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServer).GetResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chatbot_GetResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServer).GetResponse(ctx, req.(*GetResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chatbot_ServiceDesc is the grpc.ServiceDesc for Chatbot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chatbot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "easypwn.Chatbot",
	HandlerType: (*ChatbotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResponse",
			Handler:    _Chatbot_GetResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/chatbot.proto",
}
