// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/mailer.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mailer_SendConfirmationEmail_FullMethodName = "/easypwn.Mailer/SendConfirmationEmail"
	Mailer_GetConfirmationCode_FullMethodName   = "/easypwn.Mailer/GetConfirmationCode"
)

// MailerClient is the client API for Mailer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailerClient interface {
	SendConfirmationEmail(ctx context.Context, in *SendConfirmationEmailRequest, opts ...grpc.CallOption) (*SendConfirmationEmailResponse, error)
	GetConfirmationCode(ctx context.Context, in *GetConfirmationCodeRequest, opts ...grpc.CallOption) (*GetConfirmationCodeResponse, error)
}

type mailerClient struct {
	cc grpc.ClientConnInterface
}

func NewMailerClient(cc grpc.ClientConnInterface) MailerClient {
	return &mailerClient{cc}
}

func (c *mailerClient) SendConfirmationEmail(ctx context.Context, in *SendConfirmationEmailRequest, opts ...grpc.CallOption) (*SendConfirmationEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendConfirmationEmailResponse)
	err := c.cc.Invoke(ctx, Mailer_SendConfirmationEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailerClient) GetConfirmationCode(ctx context.Context, in *GetConfirmationCodeRequest, opts ...grpc.CallOption) (*GetConfirmationCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfirmationCodeResponse)
	err := c.cc.Invoke(ctx, Mailer_GetConfirmationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailerServer is the server API for Mailer service.
// All implementations must embed UnimplementedMailerServer
// for forward compatibility.
type MailerServer interface {
	SendConfirmationEmail(context.Context, *SendConfirmationEmailRequest) (*SendConfirmationEmailResponse, error)
	GetConfirmationCode(context.Context, *GetConfirmationCodeRequest) (*GetConfirmationCodeResponse, error)
	mustEmbedUnimplementedMailerServer()
}

// UnimplementedMailerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailerServer struct{}

func (UnimplementedMailerServer) SendConfirmationEmail(context.Context, *SendConfirmationEmailRequest) (*SendConfirmationEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendConfirmationEmail not implemented")
}
func (UnimplementedMailerServer) GetConfirmationCode(context.Context, *GetConfirmationCodeRequest) (*GetConfirmationCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfirmationCode not implemented")
}
func (UnimplementedMailerServer) mustEmbedUnimplementedMailerServer() {}
func (UnimplementedMailerServer) testEmbeddedByValue()                {}

// UnsafeMailerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailerServer will
// result in compilation errors.
type UnsafeMailerServer interface {
	mustEmbedUnimplementedMailerServer()
}

func RegisterMailerServer(s grpc.ServiceRegistrar, srv MailerServer) {
	// If the following call pancis, it indicates UnimplementedMailerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mailer_ServiceDesc, srv)
}

func _Mailer_SendConfirmationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendConfirmationEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerServer).SendConfirmationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mailer_SendConfirmationEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerServer).SendConfirmationEmail(ctx, req.(*SendConfirmationEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mailer_GetConfirmationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfirmationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailerServer).GetConfirmationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mailer_GetConfirmationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailerServer).GetConfirmationCode(ctx, req.(*GetConfirmationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mailer_ServiceDesc is the grpc.ServiceDesc for Mailer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mailer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "easypwn.Mailer",
	HandlerType: (*MailerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendConfirmationEmail",
			Handler:    _Mailer_SendConfirmationEmail_Handler,
		},
		{
			MethodName: "GetConfirmationCode",
			Handler:    _Mailer_GetConfirmationCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mailer.proto",
}
