CREATE TABLE IF NOT EXISTS user (
    id BINARY(16) PRIMARY KEY NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_license_type (
    id BINARY(16) PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_license (
    id BINARY(16) PRIMARY KEY NOT NULL UNIQUE,
    user_id BINARY(16) NOT NULL UNIQUE REFERENCES user(id),
    license_type_id BINARY(16) NOT NULL REFERENCES user_license_type(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

INSERT INTO user_license_type (id, name) VALUES (UUID_TO_BIN(UUID()), 'free');
INSERT INTO user_license_type (id, name) VALUES (UUID_TO_BIN(UUID()), 'paid');

CREATE TABLE IF NOT EXISTS project_os (
    id BINARY(16) PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO project_os (id, name) VALUES (UUID_TO_BIN(UUID()), 'ubuntu-2410');

CREATE TABLE IF NOT EXISTS project_plugin (
    id BINARY(16) PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO project_plugin (id, name) VALUES (UUID_TO_BIN(UUID()), 'gef');
INSERT INTO project_plugin (id, name) VALUES (UUID_TO_BIN(UUID()), 'pwndbg');

CREATE TABLE IF NOT EXISTS project (
    id BINARY(16) PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    user_id BINARY(16) NOT NULL REFERENCES user(id),
    file_path VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    os_id BINARY(16) NOT NULL REFERENCES project_os(id),
    plugin_id BINARY(16) NOT NULL REFERENCES project_plugin(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instance (
    id BINARY(16) PRIMARY KEY NOT NULL UNIQUE,
    project_id BINARY(16) NOT NULL REFERENCES project(id),
    container_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instance_log (
    id BINARY(16) PRIMARY KEY NOT NULL UNIQUE,
    instance_id BINARY(16) NOT NULL REFERENCES instance(id),
    log TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_confirmation (
    id BINARY(16) PRIMARY KEY NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);