FROM ubuntu:24.10

# install basic tools
RUN apt-get update && apt-get install -y \
    curl \
    file \
    gdb \
    python3 \
    python3-pwntools \
    vim 

# install gef
RUN bash -c "$(curl -fsSL https://gef.blah.cat/sh)"

CMD ["/bin/bash"]
