FROM ubuntu:24.10

# install basic tools
RUN apt-get update && apt-get install -y \
    curl \
    gdb \
    python3 \
    python3-pip \
    vim \
    && python3 -m pip install pwntools

# install gef
RUN bash -c "$(wget https://gef.blah.cat/sh -O -)"

CMD ["/bin/bash"]
