FROM ubuntu:24.10

# install basic tools
RUN apt-get update && apt-get install -y \
    curl \
    gdb \
    python3 \
    python3-pwntools \
    locales \
    git \
    vim 

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
RUN locale-gen en_US.UTF-8 

# install pwndbg
RUN git clone https://github.com/pwndbg/pwndbg.git /pwndbg
RUN cd /pwndbg && ./setup.sh

CMD ["/bin/bash"]
