FROM ubuntu:24.10

# install basic tools
RUN apt-get update && apt-get install -y \
    curl \
    gdb \
    python3 \
    python3-pwntools \
    locales \
    vim 

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
RUN locale-gen en_US.UTF-8 

# install pwndbg
RUN curl -L -o pwndbg_2024.08.29_amd64.deb https://github.com/pwndbg/pwndbg/releases/download/2024.08.29/pwndbg_2024.08.29_amd64.deb
RUN apt install -y ./pwndbg_2024.08.29_amd64.deb

CMD ["/bin/bash"]
