FROM ubuntu:24.10

# install basic tools
RUN apt-get update && apt-get install -y \
    curl \
    gdb \
    python3 \
    python3-pip \
    vim \
    && python3 -m pip install pwntools

# install pwndbg
RUN wget https://github.com/pwndbg/pwndbg/releases/download/2024.08.29/pwndbg_2024.08.29_amd64.deb
RUN apt install -y ./pwndbg_2024.08.29_amd64.deb

CMD ["/bin/bash"]
