CREATE TABLE IF NOT EXISTS user (
    id UUID PRIMARY KEY DEFAULT UUID(),
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_license (
    id UUID PRIMARY KEY DEFAULT UUID(),
    user_id UUID NOT NULL UNIQUE REFERENCES user(id),
    license_type_id UUID NOT NULL REFERENCES user_license_type(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_license_type (
    id UUID PRIMARY KEY DEFAULT UUID(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO user_license_type (name) VALUES ('free');
INSERT INTO user_license_type (name) VALUES ('paid');