CREATE TABLE IF NOT EXISTS user (
    id UUID PRIMARY KEY DEFAULT UUID(),
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_license (
    id UUID PRIMARY KEY DEFAULT UUID(),
    user_id UUID NOT NULL UNIQUE REFERENCES user(id),
    license_type_id UUID NOT NULL REFERENCES user_license_type(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_license_type (
    id UUID PRIMARY KEY DEFAULT UUID(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO user_license_type (name) VALUES ('free');
INSERT INTO user_license_type (name) VALUES ('paid');

CREATE TABLE IF NOT EXISTS project_os (
    id UUID PRIMARY KEY DEFAULT UUID(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO project_os (name) VALUES ('ubuntu-2410');

CREATE TABLE IF NOT EXISTS project_plugin (
    id UUID PRIMARY KEY DEFAULT UUID(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO project_plugin (name) VALUES ('gef');
INSERT INTO project_plugin (name) VALUES ('pwndbg');

CREATE TABLE IF NOT EXISTS project (
    id UUID PRIMARY KEY DEFAULT UUID(),
    name VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL REFERENCES user(id),
    file_path VARCHAR(255) NOT NULL,
    os_id UUID NOT NULL REFERENCES project_os(id),
    plugin_id UUID NOT NULL REFERENCES project_plugin(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instance (
    id UUID PRIMARY KEY DEFAULT UUID(),
    project_id UUID NOT NULL REFERENCES project(id),
    container_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instance_log (
    id UUID PRIMARY KEY DEFAULT UUID(),
    instance_id UUID NOT NULL REFERENCES instance(id),
    log TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
