name: Build and push Docker images 

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - easypwn-ping

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: repo_name
      name: Prepare image tag path
      run: echo "LOWER_GITHUB_ACTOR=${GITHUB_ACTOR,,}" >> $GITHUB_OUTPUT
      env:
        GITHUB_ACTOR: ${{ github.actor }}

    - name: Build and push ${{ matrix.image }}
      run: |
        docker build -t ghcr.io/${{ steps.repo_name.outputs.LOWER_GITHUB_ACTOR }}/${{ matrix.image }}:latest ./${{ matrix.image }}
        docker push ghcr.io/${{ steps.repo_name.outputs.LOWER_GITHUB_ACTOR }}/${{ matrix.image }}:latest
