name: Build and push Docker images 

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image:
          - instance-service
          - project-service
          - user-service
          - web

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: repo_name
      name: Prepare image tag path
      run: echo "LOWER_GITHUB_REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Build and push ${{ matrix.image }}
      run: |
        if [ "${{ matrix.image }}" = "web" ]; then
          docker build -t ghcr.io/${{ steps.repo_name.outputs.LOWER_GITHUB_REPOSITORY }}/${{ matrix.image }}:latest ./web
        else
          docker build -t ghcr.io/${{ steps.repo_name.outputs.LOWER_GITHUB_REPOSITORY }}/${{ matrix.image }}:latest ./cmd/${{ matrix.image }}
        fi
        docker push ghcr.io/${{ steps.repo_name.outputs.LOWER_GITHUB_REPOSITORY }}/${{ matrix.image }}:latest
