name: Build and push Docker images 

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - easypwn-ping

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push ${{ matrix.image }}
      run: |
        docker build -t ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest ./${{ matrix.image }}
        docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest
